// Automatically generated by hypercallgen.py
#pragma once
#include "Zookeeper.hpp"
#include "Hypercalls.hpp"

uint32_t hypercall_dispatch(uint32_t call, uint32_t addr);

class Hypercall {
public:
	uint32_t map(uint32_t virt_base, uint32_t count);
	uint32_t query_eeprom(uint32_t index);
	void unmap(uint32_t virt_base, uint32_t count);
	void log_(uint32_t message);
	uint32_t create_thread(uint32_t eip, uint32_t esp, uint32_t arg);
	uint32_t get_xbebase();
};

