// Automatically generated by hypercallgen.py
#pragma once

typedef struct hypercall_map {
	uint32_t virt_base;
	uint32_t count;
} hypercall_map_t;

typedef struct hypercall_unmap {
	uint32_t virt_base;
	uint32_t count;
} hypercall_unmap_t;

typedef struct hypercall_create_thread {
	uint32_t eip;
	uint32_t esp;
	uint32_t arg;
} hypercall_create_thread_t;

