// Automatically generated by thunkgen.py
#include "NightBeliever.hpp"

void NTAPI kernel_AvGetSavedDataAddress() {
	log("STUB AvGetSavedDataAddress");
	halt();
}

void NTAPI kernel_AvSendTVEncoderOption() {
	log("STUB AvSendTVEncoderOption");
	halt();
}

void NTAPI kernel_AvSetDisplayMode() {
	log("STUB AvSetDisplayMode");
	halt();
}

void NTAPI kernel_AvSetSavedDataAddress() {
	log("STUB AvSetSavedDataAddress");
	halt();
}

void NTAPI kernel_DbgBreakPoint() {
	log("STUB DbgBreakPoint");
	halt();
}

void NTAPI kernel_DbgBreakPointWithStatus() {
	log("STUB DbgBreakPointWithStatus");
	halt();
}

void NTAPI kernel_DbgLoadImageSymbols() {
	log("STUB DbgLoadImageSymbols");
	halt();
}

void NTAPI kernel_HalReadSMCTrayState() {
	log("STUB HalReadSMCTrayState");
	halt();
}

void NTAPI kernel_DbgPrompt() {
	log("STUB DbgPrompt");
	halt();
}

void NTAPI kernel_DbgUnLoadImageSymbols() {
	log("STUB DbgUnLoadImageSymbols");
	halt();
}

void NTAPI kernel_ExAcquireReadWriteLockExclusive() {
	log("STUB ExAcquireReadWriteLockExclusive");
	halt();
}

void NTAPI kernel_ExAcquireReadWriteLockShared() {
	log("STUB ExAcquireReadWriteLockShared");
	halt();
}

void NTAPI kernel_ExAllocatePool() {
	log("STUB ExAllocatePool");
	halt();
}

void NTAPI kernel_ExAllocatePoolWithTag() {
	log("STUB ExAllocatePoolWithTag");
	halt();
}

void NTAPI kernel_ExEventObjectType() {
	log("STUB ExEventObjectType");
	halt();
}

void NTAPI kernel_ExFreePool() {
	log("STUB ExFreePool");
	halt();
}

void NTAPI kernel_ExInitializeReadWriteLock() {
	log("STUB ExInitializeReadWriteLock");
	halt();
}

void NTAPI kernel_ExInterlockedAddLargeInteger() {
	log("STUB ExInterlockedAddLargeInteger");
	halt();
}

void NTAPI kernel_ExInterlockedAddLargeStatistic() {
	log("STUB ExInterlockedAddLargeStatistic");
	halt();
}

void NTAPI kernel_ExInterlockedCompareExchange64() {
	log("STUB ExInterlockedCompareExchange64");
	halt();
}

void NTAPI kernel_ExMutantObjectType() {
	log("STUB ExMutantObjectType");
	halt();
}

void NTAPI kernel_ExQueryPoolBlockSize() {
	log("STUB ExQueryPoolBlockSize");
	halt();
}

void NTAPI kernel_ExReadWriteRefurbInfo() {
	log("STUB ExReadWriteRefurbInfo");
	halt();
}

void NTAPI kernel_ExRaiseException() {
	log("STUB ExRaiseException");
	halt();
}

void NTAPI kernel_ExRaiseStatus() {
	log("STUB ExRaiseStatus");
	halt();
}

void NTAPI kernel_ExReleaseReadWriteLock() {
	log("STUB ExReleaseReadWriteLock");
	halt();
}

void NTAPI kernel_ExSaveNonVolatileSetting() {
	log("STUB ExSaveNonVolatileSetting");
	halt();
}

void NTAPI kernel_ExSemaphoreObjectType() {
	log("STUB ExSemaphoreObjectType");
	halt();
}

void NTAPI kernel_ExTimerObjectType() {
	log("STUB ExTimerObjectType");
	halt();
}

void NTAPI kernel_ExfInterlockedInsertHeadList() {
	log("STUB ExfInterlockedInsertHeadList");
	halt();
}

void NTAPI kernel_ExfInterlockedInsertTailList() {
	log("STUB ExfInterlockedInsertTailList");
	halt();
}

void NTAPI kernel_ExfInterlockedRemoveHeadList() {
	log("STUB ExfInterlockedRemoveHeadList");
	halt();
}

void NTAPI kernel_FscGetCacheSize() {
	log("STUB FscGetCacheSize");
	halt();
}

void NTAPI kernel_FscInvalidateIdleBlocks() {
	log("STUB FscInvalidateIdleBlocks");
	halt();
}

void NTAPI kernel_FscSetCacheSize() {
	log("STUB FscSetCacheSize");
	halt();
}

void NTAPI kernel_HalClearSoftwareInterrupt() {
	log("STUB HalClearSoftwareInterrupt");
	halt();
}

void NTAPI kernel_HalDisableSystemInterrupt() {
	log("STUB HalDisableSystemInterrupt");
	halt();
}

void NTAPI kernel_HalDiskCachePartitionCount() {
	log("STUB HalDiskCachePartitionCount");
	halt();
}

void NTAPI kernel_HalDiskModelNumber() {
	log("STUB HalDiskModelNumber");
	halt();
}

void NTAPI kernel_HalDiskSerialNumber() {
	log("STUB HalDiskSerialNumber");
	halt();
}

void NTAPI kernel_HalEnableSystemInterrupt() {
	log("STUB HalEnableSystemInterrupt");
	halt();
}

void NTAPI kernel_HalGetInterruptVector() {
	log("STUB HalGetInterruptVector");
	halt();
}

void NTAPI kernel_HalReadSMBusValue() {
	log("STUB HalReadSMBusValue");
	halt();
}

void NTAPI kernel_HalReadWritePCISpace() {
	log("STUB HalReadWritePCISpace");
	halt();
}

void NTAPI kernel_HalRequestSoftwareInterrupt() {
	log("STUB HalRequestSoftwareInterrupt");
	halt();
}

void NTAPI kernel_HalWriteSMBusValue() {
	log("STUB HalWriteSMBusValue");
	halt();
}

void NTAPI kernel_InterlockedCompareExchange() {
	log("STUB InterlockedCompareExchange");
	halt();
}

void NTAPI kernel_InterlockedDecrement() {
	log("STUB InterlockedDecrement");
	halt();
}

void NTAPI kernel_InterlockedIncrement() {
	log("STUB InterlockedIncrement");
	halt();
}

void NTAPI kernel_InterlockedExchange() {
	log("STUB InterlockedExchange");
	halt();
}

void NTAPI kernel_InterlockedExchangeAdd() {
	log("STUB InterlockedExchangeAdd");
	halt();
}

void NTAPI kernel_InterlockedFlushSList() {
	log("STUB InterlockedFlushSList");
	halt();
}

void NTAPI kernel_InterlockedPopEntrySList() {
	log("STUB InterlockedPopEntrySList");
	halt();
}

void NTAPI kernel_InterlockedPushEntrySList() {
	log("STUB InterlockedPushEntrySList");
	halt();
}

void NTAPI kernel_IoAllocateIrp() {
	log("STUB IoAllocateIrp");
	halt();
}

void NTAPI kernel_IoBuildAsynchronousFsdRequest() {
	log("STUB IoBuildAsynchronousFsdRequest");
	halt();
}

void NTAPI kernel_IoBuildDeviceIoControlRequest() {
	log("STUB IoBuildDeviceIoControlRequest");
	halt();
}

void NTAPI kernel_IoBuildSynchronousFsdRequest() {
	log("STUB IoBuildSynchronousFsdRequest");
	halt();
}

void NTAPI kernel_IoCheckShareAccess() {
	log("STUB IoCheckShareAccess");
	halt();
}

void NTAPI kernel_IoCompletionObjectType() {
	log("STUB IoCompletionObjectType");
	halt();
}

void NTAPI kernel_IoCreateDevice() {
	log("STUB IoCreateDevice");
	halt();
}

void NTAPI kernel_IoCreateFile() {
	log("STUB IoCreateFile");
	halt();
}

void NTAPI kernel_IoDeleteDevice() {
	log("STUB IoDeleteDevice");
	halt();
}

void NTAPI kernel_IoDeleteSymbolicLink() {
	log("STUB IoDeleteSymbolicLink");
	halt();
}

void NTAPI kernel_IoDeviceObjectType() {
	log("STUB IoDeviceObjectType");
	halt();
}

void NTAPI kernel_IoFileObjectType() {
	log("STUB IoFileObjectType");
	halt();
}

void NTAPI kernel_IoFreeIrp() {
	log("STUB IoFreeIrp");
	halt();
}

void NTAPI kernel_IoInitializeIrp() {
	log("STUB IoInitializeIrp");
	halt();
}

void NTAPI kernel_IoInvalidDeviceRequest() {
	log("STUB IoInvalidDeviceRequest");
	halt();
}

void NTAPI kernel_IoQueryFileInformation() {
	log("STUB IoQueryFileInformation");
	halt();
}

void NTAPI kernel_IoQueryVolumeInformation() {
	log("STUB IoQueryVolumeInformation");
	halt();
}

void NTAPI kernel_IoQueueThreadIrp() {
	log("STUB IoQueueThreadIrp");
	halt();
}

void NTAPI kernel_IoRemoveShareAccess() {
	log("STUB IoRemoveShareAccess");
	halt();
}

void NTAPI kernel_IoSetIoCompletion() {
	log("STUB IoSetIoCompletion");
	halt();
}

void NTAPI kernel_IoSetShareAccess() {
	log("STUB IoSetShareAccess");
	halt();
}

void NTAPI kernel_IoStartNextPacket() {
	log("STUB IoStartNextPacket");
	halt();
}

void NTAPI kernel_IoStartNextPacketByKey() {
	log("STUB IoStartNextPacketByKey");
	halt();
}

void NTAPI kernel_IoStartPacket() {
	log("STUB IoStartPacket");
	halt();
}

void NTAPI kernel_IoSynchronousDeviceIoControlRequest() {
	log("STUB IoSynchronousDeviceIoControlRequest");
	halt();
}

void NTAPI kernel_IoSynchronousFsdRequest() {
	log("STUB IoSynchronousFsdRequest");
	halt();
}

void NTAPI kernel_IofCallDriver() {
	log("STUB IofCallDriver");
	halt();
}

void NTAPI kernel_IofCompleteRequest() {
	log("STUB IofCompleteRequest");
	halt();
}

void NTAPI kernel_KdDebuggerEnabled() {
	log("STUB KdDebuggerEnabled");
	halt();
}

void NTAPI kernel_KdDebuggerNotPresent() {
	log("STUB KdDebuggerNotPresent");
	halt();
}

void NTAPI kernel_IoDismountVolume() {
	log("STUB IoDismountVolume");
	halt();
}

void NTAPI kernel_IoDismountVolumeByName() {
	log("STUB IoDismountVolumeByName");
	halt();
}

void NTAPI kernel_KeAlertResumeThread() {
	log("STUB KeAlertResumeThread");
	halt();
}

void NTAPI kernel_KeAlertThread() {
	log("STUB KeAlertThread");
	halt();
}

void NTAPI kernel_KeBoostPriorityThread() {
	log("STUB KeBoostPriorityThread");
	halt();
}

void NTAPI kernel_KeBugCheck() {
	log("STUB KeBugCheck");
	halt();
}

void NTAPI kernel_KeBugCheckEx() {
	log("STUB KeBugCheckEx");
	halt();
}

void NTAPI kernel_KeCancelTimer() {
	log("STUB KeCancelTimer");
	halt();
}

void NTAPI kernel_KeConnectInterrupt() {
	log("STUB KeConnectInterrupt");
	halt();
}

void NTAPI kernel_KeDelayExecutionThread() {
	log("STUB KeDelayExecutionThread");
	halt();
}

void NTAPI kernel_KeDisconnectInterrupt() {
	log("STUB KeDisconnectInterrupt");
	halt();
}

void NTAPI kernel_KeEnterCriticalRegion() {
	log("STUB KeEnterCriticalRegion");
	halt();
}

void NTAPI kernel_MmGlobalData() {
	log("STUB MmGlobalData");
	halt();
}

void NTAPI kernel_KeGetCurrentIrql() {
	log("STUB KeGetCurrentIrql");
	halt();
}

void NTAPI kernel_KeGetCurrentThread() {
	log("STUB KeGetCurrentThread");
	halt();
}

void NTAPI kernel_KeInitializeApc() {
	log("STUB KeInitializeApc");
	halt();
}

void NTAPI kernel_KeInitializeDeviceQueue() {
	log("STUB KeInitializeDeviceQueue");
	halt();
}

void NTAPI kernel_KeInitializeEvent() {
	log("STUB KeInitializeEvent");
	halt();
}

void NTAPI kernel_KeInitializeInterrupt() {
	log("STUB KeInitializeInterrupt");
	halt();
}

void NTAPI kernel_KeInitializeMutant() {
	log("STUB KeInitializeMutant");
	halt();
}

void NTAPI kernel_KeInitializeQueue() {
	log("STUB KeInitializeQueue");
	halt();
}

void NTAPI kernel_KeInitializeSemaphore() {
	log("STUB KeInitializeSemaphore");
	halt();
}

void NTAPI kernel_KeInsertByKeyDeviceQueue() {
	log("STUB KeInsertByKeyDeviceQueue");
	halt();
}

void NTAPI kernel_KeInsertDeviceQueue() {
	log("STUB KeInsertDeviceQueue");
	halt();
}

void NTAPI kernel_KeInsertHeadQueue() {
	log("STUB KeInsertHeadQueue");
	halt();
}

void NTAPI kernel_KeInsertQueue() {
	log("STUB KeInsertQueue");
	halt();
}

void NTAPI kernel_KeInsertQueueApc() {
	log("STUB KeInsertQueueApc");
	halt();
}

void NTAPI kernel_KeInsertQueueDpc() {
	log("STUB KeInsertQueueDpc");
	halt();
}

void NTAPI kernel_KeInterruptTime() {
	log("STUB KeInterruptTime");
	halt();
}

void NTAPI kernel_KeIsExecutingDpc() {
	log("STUB KeIsExecutingDpc");
	halt();
}

void NTAPI kernel_KeLeaveCriticalRegion() {
	log("STUB KeLeaveCriticalRegion");
	halt();
}

void NTAPI kernel_KePulseEvent() {
	log("STUB KePulseEvent");
	halt();
}

void NTAPI kernel_KeQueryBasePriorityThread() {
	log("STUB KeQueryBasePriorityThread");
	halt();
}

void NTAPI kernel_KeQueryInterruptTime() {
	log("STUB KeQueryInterruptTime");
	halt();
}

void NTAPI kernel_KeQueryPerformanceCounter() {
	log("STUB KeQueryPerformanceCounter");
	halt();
}

void NTAPI kernel_KeQueryPerformanceFrequency() {
	log("STUB KeQueryPerformanceFrequency");
	halt();
}

void NTAPI kernel_KeQuerySystemTime() {
	log("STUB KeQuerySystemTime");
	halt();
}

void NTAPI kernel_KeRaiseIrqlToDpcLevel() {
	log("STUB KeRaiseIrqlToDpcLevel");
	halt();
}

void NTAPI kernel_KeRaiseIrqlToSynchLevel() {
	log("STUB KeRaiseIrqlToSynchLevel");
	halt();
}

void NTAPI kernel_KeReleaseMutant() {
	log("STUB KeReleaseMutant");
	halt();
}

void NTAPI kernel_KeReleaseSemaphore() {
	log("STUB KeReleaseSemaphore");
	halt();
}

void NTAPI kernel_KeRemoveByKeyDeviceQueue() {
	log("STUB KeRemoveByKeyDeviceQueue");
	halt();
}

void NTAPI kernel_KeRemoveDeviceQueue() {
	log("STUB KeRemoveDeviceQueue");
	halt();
}

void NTAPI kernel_KeRemoveEntryDeviceQueue() {
	log("STUB KeRemoveEntryDeviceQueue");
	halt();
}

void NTAPI kernel_KeRemoveQueue() {
	log("STUB KeRemoveQueue");
	halt();
}

void NTAPI kernel_KeRemoveQueueDpc() {
	log("STUB KeRemoveQueueDpc");
	halt();
}

void NTAPI kernel_KeResetEvent() {
	log("STUB KeResetEvent");
	halt();
}

void NTAPI kernel_KeRestoreFloatingPointState() {
	log("STUB KeRestoreFloatingPointState");
	halt();
}

void NTAPI kernel_KeResumeThread() {
	log("STUB KeResumeThread");
	halt();
}

void NTAPI kernel_KeRundownQueue() {
	log("STUB KeRundownQueue");
	halt();
}

void NTAPI kernel_KeSaveFloatingPointState() {
	log("STUB KeSaveFloatingPointState");
	halt();
}

void NTAPI kernel_KeSetBasePriorityThread() {
	log("STUB KeSetBasePriorityThread");
	halt();
}

void NTAPI kernel_KeSetDisableBoostThread() {
	log("STUB KeSetDisableBoostThread");
	halt();
}

void NTAPI kernel_KeSetEvent() {
	log("STUB KeSetEvent");
	halt();
}

void NTAPI kernel_KeSetEventBoostPriority() {
	log("STUB KeSetEventBoostPriority");
	halt();
}

void NTAPI kernel_KeSetPriorityProcess() {
	log("STUB KeSetPriorityProcess");
	halt();
}

void NTAPI kernel_KeSetPriorityThread() {
	log("STUB KeSetPriorityThread");
	halt();
}

void NTAPI kernel_KeSetTimerEx() {
	log("STUB KeSetTimerEx");
	halt();
}

void NTAPI kernel_KeStallExecutionProcessor() {
	log("STUB KeStallExecutionProcessor");
	halt();
}

void NTAPI kernel_KeSuspendThread() {
	log("STUB KeSuspendThread");
	halt();
}

void NTAPI kernel_KeSynchronizeExecution() {
	log("STUB KeSynchronizeExecution");
	halt();
}

void NTAPI kernel_KeSystemTime() {
	log("STUB KeSystemTime");
	halt();
}

void NTAPI kernel_KeTestAlertThread() {
	log("STUB KeTestAlertThread");
	halt();
}

void NTAPI kernel_KeTickCount() {
	log("STUB KeTickCount");
	halt();
}

void NTAPI kernel_KeTimeIncrement() {
	log("STUB KeTimeIncrement");
	halt();
}

void NTAPI kernel_KeWaitForMultipleObjects() {
	log("STUB KeWaitForMultipleObjects");
	halt();
}

void NTAPI kernel_KeWaitForSingleObject() {
	log("STUB KeWaitForSingleObject");
	halt();
}

void NTAPI kernel_KfRaiseIrql() {
	log("STUB KfRaiseIrql");
	halt();
}

void NTAPI kernel_KfLowerIrql() {
	log("STUB KfLowerIrql");
	halt();
}

void NTAPI kernel_KiBugCheckData() {
	log("STUB KiBugCheckData");
	halt();
}

void NTAPI kernel_KiUnlockDispatcherDatabase() {
	log("STUB KiUnlockDispatcherDatabase");
	halt();
}

void NTAPI kernel_MmAllocateContiguousMemoryEx() {
	log("STUB MmAllocateContiguousMemoryEx");
	halt();
}

void NTAPI kernel_MmAllocateSystemMemory() {
	log("STUB MmAllocateSystemMemory");
	halt();
}

void NTAPI kernel_MmClaimGpuInstanceMemory() {
	log("STUB MmClaimGpuInstanceMemory");
	halt();
}

void NTAPI kernel_MmCreateKernelStack() {
	log("STUB MmCreateKernelStack");
	halt();
}

void NTAPI kernel_MmDeleteKernelStack() {
	log("STUB MmDeleteKernelStack");
	halt();
}

void NTAPI kernel_MmFreeContiguousMemory() {
	log("STUB MmFreeContiguousMemory");
	halt();
}

void NTAPI kernel_MmFreeSystemMemory() {
	log("STUB MmFreeSystemMemory");
	halt();
}

void NTAPI kernel_MmGetPhysicalAddress() {
	log("STUB MmGetPhysicalAddress");
	halt();
}

void NTAPI kernel_MmIsAddressValid() {
	log("STUB MmIsAddressValid");
	halt();
}

void NTAPI kernel_MmLockUnlockBufferPages() {
	log("STUB MmLockUnlockBufferPages");
	halt();
}

void NTAPI kernel_MmLockUnlockPhysicalPage() {
	log("STUB MmLockUnlockPhysicalPage");
	halt();
}

void NTAPI kernel_MmMapIoSpace() {
	log("STUB MmMapIoSpace");
	halt();
}

void NTAPI kernel_MmQueryAddressProtect() {
	log("STUB MmQueryAddressProtect");
	halt();
}

void NTAPI kernel_MmQueryAllocationSize() {
	log("STUB MmQueryAllocationSize");
	halt();
}

void NTAPI kernel_MmQueryStatistics() {
	log("STUB MmQueryStatistics");
	halt();
}

void NTAPI kernel_MmSetAddressProtect() {
	log("STUB MmSetAddressProtect");
	halt();
}

void NTAPI kernel_MmUnmapIoSpace() {
	log("STUB MmUnmapIoSpace");
	halt();
}

void NTAPI kernel_NtCancelTimer() {
	log("STUB NtCancelTimer");
	halt();
}

void NTAPI kernel_NtClearEvent() {
	log("STUB NtClearEvent");
	halt();
}

void NTAPI kernel_NtCreateDirectoryObject() {
	log("STUB NtCreateDirectoryObject");
	halt();
}

void NTAPI kernel_NtCreateEvent() {
	log("STUB NtCreateEvent");
	halt();
}

void NTAPI kernel_NtCreateIoCompletion() {
	log("STUB NtCreateIoCompletion");
	halt();
}

void NTAPI kernel_NtCreateMutant() {
	log("STUB NtCreateMutant");
	halt();
}

void NTAPI kernel_NtCreateSemaphore() {
	log("STUB NtCreateSemaphore");
	halt();
}

void NTAPI kernel_NtCreateTimer() {
	log("STUB NtCreateTimer");
	halt();
}

void NTAPI kernel_NtDeleteFile() {
	log("STUB NtDeleteFile");
	halt();
}

void NTAPI kernel_NtDeviceIoControlFile() {
	log("STUB NtDeviceIoControlFile");
	halt();
}

void NTAPI kernel_NtDuplicateObject() {
	log("STUB NtDuplicateObject");
	halt();
}

void NTAPI kernel_NtFlushBuffersFile() {
	log("STUB NtFlushBuffersFile");
	halt();
}

void NTAPI kernel_NtFreeVirtualMemory() {
	log("STUB NtFreeVirtualMemory");
	halt();
}

void NTAPI kernel_NtFsControlFile() {
	log("STUB NtFsControlFile");
	halt();
}

void NTAPI kernel_NtOpenDirectoryObject() {
	log("STUB NtOpenDirectoryObject");
	halt();
}

void NTAPI kernel_NtOpenSymbolicLinkObject() {
	log("STUB NtOpenSymbolicLinkObject");
	halt();
}

void NTAPI kernel_NtProtectVirtualMemory() {
	log("STUB NtProtectVirtualMemory");
	halt();
}

void NTAPI kernel_NtPulseEvent() {
	log("STUB NtPulseEvent");
	halt();
}

void NTAPI kernel_NtQueueApcThread() {
	log("STUB NtQueueApcThread");
	halt();
}

void NTAPI kernel_NtQueryDirectoryFile() {
	log("STUB NtQueryDirectoryFile");
	halt();
}

void NTAPI kernel_NtQueryDirectoryObject() {
	log("STUB NtQueryDirectoryObject");
	halt();
}

void NTAPI kernel_NtQueryEvent() {
	log("STUB NtQueryEvent");
	halt();
}

void NTAPI kernel_NtQueryFullAttributesFile() {
	log("STUB NtQueryFullAttributesFile");
	halt();
}

void NTAPI kernel_NtQueryInformationFile() {
	log("STUB NtQueryInformationFile");
	halt();
}

void NTAPI kernel_NtQueryIoCompletion() {
	log("STUB NtQueryIoCompletion");
	halt();
}

void NTAPI kernel_NtQueryMutant() {
	log("STUB NtQueryMutant");
	halt();
}

void NTAPI kernel_NtQuerySemaphore() {
	log("STUB NtQuerySemaphore");
	halt();
}

void NTAPI kernel_NtQuerySymbolicLinkObject() {
	log("STUB NtQuerySymbolicLinkObject");
	halt();
}

void NTAPI kernel_NtQueryTimer() {
	log("STUB NtQueryTimer");
	halt();
}

void NTAPI kernel_NtQueryVirtualMemory() {
	log("STUB NtQueryVirtualMemory");
	halt();
}

void NTAPI kernel_NtReadFile() {
	log("STUB NtReadFile");
	halt();
}

void NTAPI kernel_NtReadFileScatter() {
	log("STUB NtReadFileScatter");
	halt();
}

void NTAPI kernel_NtReleaseMutant() {
	log("STUB NtReleaseMutant");
	halt();
}

void NTAPI kernel_NtReleaseSemaphore() {
	log("STUB NtReleaseSemaphore");
	halt();
}

void NTAPI kernel_NtRemoveIoCompletion() {
	log("STUB NtRemoveIoCompletion");
	halt();
}

void NTAPI kernel_NtResumeThread() {
	log("STUB NtResumeThread");
	halt();
}

void NTAPI kernel_NtSetEvent() {
	log("STUB NtSetEvent");
	halt();
}

void NTAPI kernel_NtSetInformationFile() {
	log("STUB NtSetInformationFile");
	halt();
}

void NTAPI kernel_NtSetIoCompletion() {
	log("STUB NtSetIoCompletion");
	halt();
}

void NTAPI kernel_NtSetSystemTime() {
	log("STUB NtSetSystemTime");
	halt();
}

void NTAPI kernel_NtSetTimerEx() {
	log("STUB NtSetTimerEx");
	halt();
}

void NTAPI kernel_NtSignalAndWaitForSingleObjectEx() {
	log("STUB NtSignalAndWaitForSingleObjectEx");
	halt();
}

void NTAPI kernel_NtSuspendThread() {
	log("STUB NtSuspendThread");
	halt();
}

void NTAPI kernel_NtUserIoApcDispatcher() {
	log("STUB NtUserIoApcDispatcher");
	halt();
}

void NTAPI kernel_NtWaitForSingleObject() {
	log("STUB NtWaitForSingleObject");
	halt();
}

void NTAPI kernel_NtWaitForSingleObjectEx() {
	log("STUB NtWaitForSingleObjectEx");
	halt();
}

void NTAPI kernel_NtWaitForMultipleObjectsEx() {
	log("STUB NtWaitForMultipleObjectsEx");
	halt();
}

void NTAPI kernel_NtWriteFile() {
	log("STUB NtWriteFile");
	halt();
}

void NTAPI kernel_NtWriteFileGather() {
	log("STUB NtWriteFileGather");
	halt();
}

void NTAPI kernel_NtYieldExecution() {
	log("STUB NtYieldExecution");
	halt();
}

void NTAPI kernel_ObCreateObject() {
	log("STUB ObCreateObject");
	halt();
}

void NTAPI kernel_ObDirectoryObjectType() {
	log("STUB ObDirectoryObjectType");
	halt();
}

void NTAPI kernel_ObInsertObject() {
	log("STUB ObInsertObject");
	halt();
}

void NTAPI kernel_ObMakeTemporaryObject() {
	log("STUB ObMakeTemporaryObject");
	halt();
}

void NTAPI kernel_ObOpenObjectByName() {
	log("STUB ObOpenObjectByName");
	halt();
}

void NTAPI kernel_ObOpenObjectByPointer() {
	log("STUB ObOpenObjectByPointer");
	halt();
}

void NTAPI kernel_ObpObjectHandleTable() {
	log("STUB ObpObjectHandleTable");
	halt();
}

void NTAPI kernel_ObReferenceObjectByHandle() {
	log("STUB ObReferenceObjectByHandle");
	halt();
}

void NTAPI kernel_ObReferenceObjectByName() {
	log("STUB ObReferenceObjectByName");
	halt();
}

void NTAPI kernel_ObReferenceObjectByPointer() {
	log("STUB ObReferenceObjectByPointer");
	halt();
}

void NTAPI kernel_ObSymbolicLinkObjectType() {
	log("STUB ObSymbolicLinkObjectType");
	halt();
}

void NTAPI kernel_ObfDereferenceObject() {
	log("STUB ObfDereferenceObject");
	halt();
}

void NTAPI kernel_ObfReferenceObject() {
	log("STUB ObfReferenceObject");
	halt();
}

void NTAPI kernel_PhyGetLinkState() {
	log("STUB PhyGetLinkState");
	halt();
}

void NTAPI kernel_PhyInitialize() {
	log("STUB PhyInitialize");
	halt();
}

void NTAPI kernel_PsCreateSystemThread() {
	log("STUB PsCreateSystemThread");
	halt();
}

void NTAPI kernel_PsQueryStatistics() {
	log("STUB PsQueryStatistics");
	halt();
}

void NTAPI kernel_PsSetCreateThreadNotifyRoutine() {
	log("STUB PsSetCreateThreadNotifyRoutine");
	halt();
}

void NTAPI kernel_PsTerminateSystemThread() {
	log("STUB PsTerminateSystemThread");
	halt();
}

void NTAPI kernel_PsThreadObjectType() {
	log("STUB PsThreadObjectType");
	halt();
}

void NTAPI kernel_RtlAnsiStringToUnicodeString() {
	log("STUB RtlAnsiStringToUnicodeString");
	halt();
}

void NTAPI kernel_RtlAppendStringToString() {
	log("STUB RtlAppendStringToString");
	halt();
}

void NTAPI kernel_RtlAppendUnicodeStringToString() {
	log("STUB RtlAppendUnicodeStringToString");
	halt();
}

void NTAPI kernel_RtlAppendUnicodeToString() {
	log("STUB RtlAppendUnicodeToString");
	halt();
}

void NTAPI kernel_RtlCaptureContext() {
	log("STUB RtlCaptureContext");
	halt();
}

void NTAPI kernel_RtlCaptureStackBackTrace() {
	log("STUB RtlCaptureStackBackTrace");
	halt();
}

void NTAPI kernel_RtlCharToInteger() {
	log("STUB RtlCharToInteger");
	halt();
}

void NTAPI kernel_RtlCompareMemory() {
	log("STUB RtlCompareMemory");
	halt();
}

void NTAPI kernel_RtlCompareMemoryUlong() {
	log("STUB RtlCompareMemoryUlong");
	halt();
}

void NTAPI kernel_RtlCompareString() {
	log("STUB RtlCompareString");
	halt();
}

void NTAPI kernel_RtlCompareUnicodeString() {
	log("STUB RtlCompareUnicodeString");
	halt();
}

void NTAPI kernel_RtlCopyString() {
	log("STUB RtlCopyString");
	halt();
}

void NTAPI kernel_RtlCopyUnicodeString() {
	log("STUB RtlCopyUnicodeString");
	halt();
}

void NTAPI kernel_RtlCreateUnicodeString() {
	log("STUB RtlCreateUnicodeString");
	halt();
}

void NTAPI kernel_RtlDowncaseUnicodeChar() {
	log("STUB RtlDowncaseUnicodeChar");
	halt();
}

void NTAPI kernel_RtlDowncaseUnicodeString() {
	log("STUB RtlDowncaseUnicodeString");
	halt();
}

void NTAPI kernel_RtlEnterCriticalSectionAndRegion() {
	log("STUB RtlEnterCriticalSectionAndRegion");
	halt();
}

void NTAPI kernel_RtlEqualString() {
	log("STUB RtlEqualString");
	halt();
}

void NTAPI kernel_RtlEqualUnicodeString() {
	log("STUB RtlEqualUnicodeString");
	halt();
}

void NTAPI kernel_RtlExtendedIntegerMultiply() {
	log("STUB RtlExtendedIntegerMultiply");
	halt();
}

void NTAPI kernel_RtlExtendedLargeIntegerDivide() {
	log("STUB RtlExtendedLargeIntegerDivide");
	halt();
}

void NTAPI kernel_RtlExtendedMagicDivide() {
	log("STUB RtlExtendedMagicDivide");
	halt();
}

void NTAPI kernel_RtlFillMemory() {
	log("STUB RtlFillMemory");
	halt();
}

void NTAPI kernel_RtlFillMemoryUlong() {
	log("STUB RtlFillMemoryUlong");
	halt();
}

void NTAPI kernel_RtlFreeAnsiString() {
	log("STUB RtlFreeAnsiString");
	halt();
}

void NTAPI kernel_RtlFreeUnicodeString() {
	log("STUB RtlFreeUnicodeString");
	halt();
}

void NTAPI kernel_RtlGetCallersAddress() {
	log("STUB RtlGetCallersAddress");
	halt();
}

void NTAPI kernel_RtlInitAnsiString() {
	log("STUB RtlInitAnsiString");
	halt();
}

void NTAPI kernel_RtlInitUnicodeString() {
	log("STUB RtlInitUnicodeString");
	halt();
}

void NTAPI kernel_RtlIntegerToChar() {
	log("STUB RtlIntegerToChar");
	halt();
}

void NTAPI kernel_RtlIntegerToUnicodeString() {
	log("STUB RtlIntegerToUnicodeString");
	halt();
}

void NTAPI kernel_RtlLeaveCriticalSectionAndRegion() {
	log("STUB RtlLeaveCriticalSectionAndRegion");
	halt();
}

void NTAPI kernel_RtlLowerChar() {
	log("STUB RtlLowerChar");
	halt();
}

void NTAPI kernel_RtlMapGenericMask() {
	log("STUB RtlMapGenericMask");
	halt();
}

void NTAPI kernel_RtlMoveMemory() {
	log("STUB RtlMoveMemory");
	halt();
}

void NTAPI kernel_RtlMultiByteToUnicodeN() {
	log("STUB RtlMultiByteToUnicodeN");
	halt();
}

void NTAPI kernel_RtlMultiByteToUnicodeSize() {
	log("STUB RtlMultiByteToUnicodeSize");
	halt();
}

void NTAPI kernel_RtlRaiseException() {
	log("STUB RtlRaiseException");
	halt();
}

void NTAPI kernel_RtlRaiseStatus() {
	log("STUB RtlRaiseStatus");
	halt();
}

void NTAPI kernel_RtlTimeFieldsToTime() {
	log("STUB RtlTimeFieldsToTime");
	halt();
}

void NTAPI kernel_RtlTimeToTimeFields() {
	log("STUB RtlTimeToTimeFields");
	halt();
}

void NTAPI kernel_RtlTryEnterCriticalSection() {
	log("STUB RtlTryEnterCriticalSection");
	halt();
}

void NTAPI kernel_RtlUlongByteSwap() {
	log("STUB RtlUlongByteSwap");
	halt();
}

void NTAPI kernel_RtlUnicodeStringToAnsiString() {
	log("STUB RtlUnicodeStringToAnsiString");
	halt();
}

void NTAPI kernel_RtlUnicodeStringToInteger() {
	log("STUB RtlUnicodeStringToInteger");
	halt();
}

void NTAPI kernel_RtlUnicodeToMultiByteN() {
	log("STUB RtlUnicodeToMultiByteN");
	halt();
}

void NTAPI kernel_RtlUnicodeToMultiByteSize() {
	log("STUB RtlUnicodeToMultiByteSize");
	halt();
}

void NTAPI kernel_RtlUnwind() {
	log("STUB RtlUnwind");
	halt();
}

void NTAPI kernel_RtlUpcaseUnicodeChar() {
	log("STUB RtlUpcaseUnicodeChar");
	halt();
}

void NTAPI kernel_RtlUpcaseUnicodeString() {
	log("STUB RtlUpcaseUnicodeString");
	halt();
}

void NTAPI kernel_RtlUpcaseUnicodeToMultiByteN() {
	log("STUB RtlUpcaseUnicodeToMultiByteN");
	halt();
}

void NTAPI kernel_RtlUpperChar() {
	log("STUB RtlUpperChar");
	halt();
}

void NTAPI kernel_RtlUpperString() {
	log("STUB RtlUpperString");
	halt();
}

void NTAPI kernel_RtlUshortByteSwap() {
	log("STUB RtlUshortByteSwap");
	halt();
}

void NTAPI kernel_RtlWalkFrameChain() {
	log("STUB RtlWalkFrameChain");
	halt();
}

void NTAPI kernel_RtlZeroMemory() {
	log("STUB RtlZeroMemory");
	halt();
}

void NTAPI kernel_XboxEEPROMKey() {
	log("STUB XboxEEPROMKey");
	halt();
}

void NTAPI kernel_XboxHDKey() {
	log("STUB XboxHDKey");
	halt();
}

void NTAPI kernel_XboxSignatureKey() {
	log("STUB XboxSignatureKey");
	halt();
}

void NTAPI kernel_XeImageFileName() {
	log("STUB XeImageFileName");
	halt();
}

void NTAPI kernel_XeLoadSection() {
	log("STUB XeLoadSection");
	halt();
}

void NTAPI kernel_XeUnloadSection() {
	log("STUB XeUnloadSection");
	halt();
}

void NTAPI kernel_READ_PORT_BUFFER_UCHAR() {
	log("STUB READ_PORT_BUFFER_UCHAR");
	halt();
}

void NTAPI kernel_READ_PORT_BUFFER_USHORT() {
	log("STUB READ_PORT_BUFFER_USHORT");
	halt();
}

void NTAPI kernel_READ_PORT_BUFFER_ULONG() {
	log("STUB READ_PORT_BUFFER_ULONG");
	halt();
}

void NTAPI kernel_WRITE_PORT_BUFFER_UCHAR() {
	log("STUB WRITE_PORT_BUFFER_UCHAR");
	halt();
}

void NTAPI kernel_WRITE_PORT_BUFFER_USHORT() {
	log("STUB WRITE_PORT_BUFFER_USHORT");
	halt();
}

void NTAPI kernel_WRITE_PORT_BUFFER_ULONG() {
	log("STUB WRITE_PORT_BUFFER_ULONG");
	halt();
}

void NTAPI kernel_XcSHAInit() {
	log("STUB XcSHAInit");
	halt();
}

void NTAPI kernel_XcSHAUpdate() {
	log("STUB XcSHAUpdate");
	halt();
}

void NTAPI kernel_XcSHAFinal() {
	log("STUB XcSHAFinal");
	halt();
}

void NTAPI kernel_XcRC4Key() {
	log("STUB XcRC4Key");
	halt();
}

void NTAPI kernel_XcRC4Crypt() {
	log("STUB XcRC4Crypt");
	halt();
}

void NTAPI kernel_XcHMAC() {
	log("STUB XcHMAC");
	halt();
}

void NTAPI kernel_XcPKEncPublic() {
	log("STUB XcPKEncPublic");
	halt();
}

void NTAPI kernel_XcPKDecPrivate() {
	log("STUB XcPKDecPrivate");
	halt();
}

void NTAPI kernel_XcPKGetKeyLen() {
	log("STUB XcPKGetKeyLen");
	halt();
}

void NTAPI kernel_XcVerifyPKCS1Signature() {
	log("STUB XcVerifyPKCS1Signature");
	halt();
}

void NTAPI kernel_XcModExp() {
	log("STUB XcModExp");
	halt();
}

void NTAPI kernel_XcDESKeyParity() {
	log("STUB XcDESKeyParity");
	halt();
}

void NTAPI kernel_XcKeyTable() {
	log("STUB XcKeyTable");
	halt();
}

void NTAPI kernel_XcBlockCrypt() {
	log("STUB XcBlockCrypt");
	halt();
}

void NTAPI kernel_XcBlockCryptCBC() {
	log("STUB XcBlockCryptCBC");
	halt();
}

void NTAPI kernel_XcCryptService() {
	log("STUB XcCryptService");
	halt();
}

void NTAPI kernel_XcUpdateCrypto() {
	log("STUB XcUpdateCrypto");
	halt();
}

void NTAPI kernel_RtlRip() {
	log("STUB RtlRip");
	halt();
}

void NTAPI kernel_XboxLANKey() {
	log("STUB XboxLANKey");
	halt();
}

void NTAPI kernel_XboxAlternateSignatureKeys() {
	log("STUB XboxAlternateSignatureKeys");
	halt();
}

void NTAPI kernel_XePublicKeyData() {
	log("STUB XePublicKeyData");
	halt();
}

void NTAPI kernel_HalBootSMCVideoMode() {
	log("STUB HalBootSMCVideoMode");
	halt();
}

void NTAPI kernel_HalIsResetOrShutdownPending() {
	log("STUB HalIsResetOrShutdownPending");
	halt();
}

void NTAPI kernel_IoMarkIrpMustComplete() {
	log("STUB IoMarkIrpMustComplete");
	halt();
}

void NTAPI kernel_HalInitiateShutdown() {
	log("STUB HalInitiateShutdown");
	halt();
}

void NTAPI kernel_snprintf() {
	log("STUB snprintf");
	halt();
}

void NTAPI kernel_sprintf() {
	log("STUB sprintf");
	halt();
}

void NTAPI kernel_vsnprintf() {
	log("STUB vsnprintf");
	halt();
}

void NTAPI kernel_vsprintf() {
	log("STUB vsprintf");
	halt();
}

void NTAPI kernel_HalEnableSecureTrayEject() {
	log("STUB HalEnableSecureTrayEject");
	halt();
}

void NTAPI kernel_HalWriteSMCScratchRegister() {
	log("STUB HalWriteSMCScratchRegister");
	halt();
}

uint32_t thunk_lookup(uint32_t id) {
	switch(id) {
		case 0x80000001: return (uint32_t) &kernel_AvGetSavedDataAddress;
		case 0x80000002: return (uint32_t) &kernel_AvSendTVEncoderOption;
		case 0x80000003: return (uint32_t) &kernel_AvSetDisplayMode;
		case 0x80000004: return (uint32_t) &kernel_AvSetSavedDataAddress;
		case 0x80000005: return (uint32_t) &kernel_DbgBreakPoint;
		case 0x80000006: return (uint32_t) &kernel_DbgBreakPointWithStatus;
		case 0x80000007: return (uint32_t) &kernel_DbgLoadImageSymbols;
		case 0x80000008: return (uint32_t) &kernel_DbgPrint;
		case 0x80000009: return (uint32_t) &kernel_HalReadSMCTrayState;
		case 0x8000000a: return (uint32_t) &kernel_DbgPrompt;
		case 0x8000000b: return (uint32_t) &kernel_DbgUnLoadImageSymbols;
		case 0x8000000c: return (uint32_t) &kernel_ExAcquireReadWriteLockExclusive;
		case 0x8000000d: return (uint32_t) &kernel_ExAcquireReadWriteLockShared;
		case 0x8000000e: return (uint32_t) &kernel_ExAllocatePool;
		case 0x8000000f: return (uint32_t) &kernel_ExAllocatePoolWithTag;
		case 0x80000010: return (uint32_t) &kernel_ExEventObjectType;
		case 0x80000011: return (uint32_t) &kernel_ExFreePool;
		case 0x80000012: return (uint32_t) &kernel_ExInitializeReadWriteLock;
		case 0x80000013: return (uint32_t) &kernel_ExInterlockedAddLargeInteger;
		case 0x80000014: return (uint32_t) &kernel_ExInterlockedAddLargeStatistic;
		case 0x80000015: return (uint32_t) &kernel_ExInterlockedCompareExchange64;
		case 0x80000016: return (uint32_t) &kernel_ExMutantObjectType;
		case 0x80000017: return (uint32_t) &kernel_ExQueryPoolBlockSize;
		case 0x80000018: return (uint32_t) &kernel_ExQueryNonVolatileSetting;
		case 0x80000019: return (uint32_t) &kernel_ExReadWriteRefurbInfo;
		case 0x8000001a: return (uint32_t) &kernel_ExRaiseException;
		case 0x8000001b: return (uint32_t) &kernel_ExRaiseStatus;
		case 0x8000001c: return (uint32_t) &kernel_ExReleaseReadWriteLock;
		case 0x8000001d: return (uint32_t) &kernel_ExSaveNonVolatileSetting;
		case 0x8000001e: return (uint32_t) &kernel_ExSemaphoreObjectType;
		case 0x8000001f: return (uint32_t) &kernel_ExTimerObjectType;
		case 0x80000020: return (uint32_t) &kernel_ExfInterlockedInsertHeadList;
		case 0x80000021: return (uint32_t) &kernel_ExfInterlockedInsertTailList;
		case 0x80000022: return (uint32_t) &kernel_ExfInterlockedRemoveHeadList;
		case 0x80000023: return (uint32_t) &kernel_FscGetCacheSize;
		case 0x80000024: return (uint32_t) &kernel_FscInvalidateIdleBlocks;
		case 0x80000025: return (uint32_t) &kernel_FscSetCacheSize;
		case 0x80000026: return (uint32_t) &kernel_HalClearSoftwareInterrupt;
		case 0x80000027: return (uint32_t) &kernel_HalDisableSystemInterrupt;
		case 0x80000028: return (uint32_t) &kernel_HalDiskCachePartitionCount;
		case 0x80000029: return (uint32_t) &kernel_HalDiskModelNumber;
		case 0x8000002a: return (uint32_t) &kernel_HalDiskSerialNumber;
		case 0x8000002b: return (uint32_t) &kernel_HalEnableSystemInterrupt;
		case 0x8000002c: return (uint32_t) &kernel_HalGetInterruptVector;
		case 0x8000002d: return (uint32_t) &kernel_HalReadSMBusValue;
		case 0x8000002e: return (uint32_t) &kernel_HalReadWritePCISpace;
		case 0x8000002f: return (uint32_t) &kernel_HalRegisterShutdownNotification;
		case 0x80000030: return (uint32_t) &kernel_HalRequestSoftwareInterrupt;
		case 0x80000031: return (uint32_t) &kernel_HalReturnToFirmware;
		case 0x80000032: return (uint32_t) &kernel_HalWriteSMBusValue;
		case 0x80000033: return (uint32_t) &kernel_InterlockedCompareExchange;
		case 0x80000034: return (uint32_t) &kernel_InterlockedDecrement;
		case 0x80000035: return (uint32_t) &kernel_InterlockedIncrement;
		case 0x80000036: return (uint32_t) &kernel_InterlockedExchange;
		case 0x80000037: return (uint32_t) &kernel_InterlockedExchangeAdd;
		case 0x80000038: return (uint32_t) &kernel_InterlockedFlushSList;
		case 0x80000039: return (uint32_t) &kernel_InterlockedPopEntrySList;
		case 0x8000003a: return (uint32_t) &kernel_InterlockedPushEntrySList;
		case 0x8000003b: return (uint32_t) &kernel_IoAllocateIrp;
		case 0x8000003c: return (uint32_t) &kernel_IoBuildAsynchronousFsdRequest;
		case 0x8000003d: return (uint32_t) &kernel_IoBuildDeviceIoControlRequest;
		case 0x8000003e: return (uint32_t) &kernel_IoBuildSynchronousFsdRequest;
		case 0x8000003f: return (uint32_t) &kernel_IoCheckShareAccess;
		case 0x80000040: return (uint32_t) &kernel_IoCompletionObjectType;
		case 0x80000041: return (uint32_t) &kernel_IoCreateDevice;
		case 0x80000042: return (uint32_t) &kernel_IoCreateFile;
		case 0x80000043: return (uint32_t) &kernel_IoCreateSymbolicLink;
		case 0x80000044: return (uint32_t) &kernel_IoDeleteDevice;
		case 0x80000045: return (uint32_t) &kernel_IoDeleteSymbolicLink;
		case 0x80000046: return (uint32_t) &kernel_IoDeviceObjectType;
		case 0x80000047: return (uint32_t) &kernel_IoFileObjectType;
		case 0x80000048: return (uint32_t) &kernel_IoFreeIrp;
		case 0x80000049: return (uint32_t) &kernel_IoInitializeIrp;
		case 0x8000004a: return (uint32_t) &kernel_IoInvalidDeviceRequest;
		case 0x8000004b: return (uint32_t) &kernel_IoQueryFileInformation;
		case 0x8000004c: return (uint32_t) &kernel_IoQueryVolumeInformation;
		case 0x8000004d: return (uint32_t) &kernel_IoQueueThreadIrp;
		case 0x8000004e: return (uint32_t) &kernel_IoRemoveShareAccess;
		case 0x8000004f: return (uint32_t) &kernel_IoSetIoCompletion;
		case 0x80000050: return (uint32_t) &kernel_IoSetShareAccess;
		case 0x80000051: return (uint32_t) &kernel_IoStartNextPacket;
		case 0x80000052: return (uint32_t) &kernel_IoStartNextPacketByKey;
		case 0x80000053: return (uint32_t) &kernel_IoStartPacket;
		case 0x80000054: return (uint32_t) &kernel_IoSynchronousDeviceIoControlRequest;
		case 0x80000055: return (uint32_t) &kernel_IoSynchronousFsdRequest;
		case 0x80000056: return (uint32_t) &kernel_IofCallDriver;
		case 0x80000057: return (uint32_t) &kernel_IofCompleteRequest;
		case 0x80000058: return (uint32_t) &kernel_KdDebuggerEnabled;
		case 0x80000059: return (uint32_t) &kernel_KdDebuggerNotPresent;
		case 0x8000005a: return (uint32_t) &kernel_IoDismountVolume;
		case 0x8000005b: return (uint32_t) &kernel_IoDismountVolumeByName;
		case 0x8000005c: return (uint32_t) &kernel_KeAlertResumeThread;
		case 0x8000005d: return (uint32_t) &kernel_KeAlertThread;
		case 0x8000005e: return (uint32_t) &kernel_KeBoostPriorityThread;
		case 0x8000005f: return (uint32_t) &kernel_KeBugCheck;
		case 0x80000060: return (uint32_t) &kernel_KeBugCheckEx;
		case 0x80000061: return (uint32_t) &kernel_KeCancelTimer;
		case 0x80000062: return (uint32_t) &kernel_KeConnectInterrupt;
		case 0x80000063: return (uint32_t) &kernel_KeDelayExecutionThread;
		case 0x80000064: return (uint32_t) &kernel_KeDisconnectInterrupt;
		case 0x80000065: return (uint32_t) &kernel_KeEnterCriticalRegion;
		case 0x80000066: return (uint32_t) &kernel_MmGlobalData;
		case 0x80000067: return (uint32_t) &kernel_KeGetCurrentIrql;
		case 0x80000068: return (uint32_t) &kernel_KeGetCurrentThread;
		case 0x80000069: return (uint32_t) &kernel_KeInitializeApc;
		case 0x8000006a: return (uint32_t) &kernel_KeInitializeDeviceQueue;
		case 0x8000006b: return (uint32_t) &kernel_KeInitializeDpc;
		case 0x8000006c: return (uint32_t) &kernel_KeInitializeEvent;
		case 0x8000006d: return (uint32_t) &kernel_KeInitializeInterrupt;
		case 0x8000006e: return (uint32_t) &kernel_KeInitializeMutant;
		case 0x8000006f: return (uint32_t) &kernel_KeInitializeQueue;
		case 0x80000070: return (uint32_t) &kernel_KeInitializeSemaphore;
		case 0x80000071: return (uint32_t) &kernel_KeInitializeTimerEx;
		case 0x80000072: return (uint32_t) &kernel_KeInsertByKeyDeviceQueue;
		case 0x80000073: return (uint32_t) &kernel_KeInsertDeviceQueue;
		case 0x80000074: return (uint32_t) &kernel_KeInsertHeadQueue;
		case 0x80000075: return (uint32_t) &kernel_KeInsertQueue;
		case 0x80000076: return (uint32_t) &kernel_KeInsertQueueApc;
		case 0x80000077: return (uint32_t) &kernel_KeInsertQueueDpc;
		case 0x80000078: return (uint32_t) &kernel_KeInterruptTime;
		case 0x80000079: return (uint32_t) &kernel_KeIsExecutingDpc;
		case 0x8000007a: return (uint32_t) &kernel_KeLeaveCriticalRegion;
		case 0x8000007b: return (uint32_t) &kernel_KePulseEvent;
		case 0x8000007c: return (uint32_t) &kernel_KeQueryBasePriorityThread;
		case 0x8000007d: return (uint32_t) &kernel_KeQueryInterruptTime;
		case 0x8000007e: return (uint32_t) &kernel_KeQueryPerformanceCounter;
		case 0x8000007f: return (uint32_t) &kernel_KeQueryPerformanceFrequency;
		case 0x80000080: return (uint32_t) &kernel_KeQuerySystemTime;
		case 0x80000081: return (uint32_t) &kernel_KeRaiseIrqlToDpcLevel;
		case 0x80000082: return (uint32_t) &kernel_KeRaiseIrqlToSynchLevel;
		case 0x80000083: return (uint32_t) &kernel_KeReleaseMutant;
		case 0x80000084: return (uint32_t) &kernel_KeReleaseSemaphore;
		case 0x80000085: return (uint32_t) &kernel_KeRemoveByKeyDeviceQueue;
		case 0x80000086: return (uint32_t) &kernel_KeRemoveDeviceQueue;
		case 0x80000087: return (uint32_t) &kernel_KeRemoveEntryDeviceQueue;
		case 0x80000088: return (uint32_t) &kernel_KeRemoveQueue;
		case 0x80000089: return (uint32_t) &kernel_KeRemoveQueueDpc;
		case 0x8000008a: return (uint32_t) &kernel_KeResetEvent;
		case 0x8000008b: return (uint32_t) &kernel_KeRestoreFloatingPointState;
		case 0x8000008c: return (uint32_t) &kernel_KeResumeThread;
		case 0x8000008d: return (uint32_t) &kernel_KeRundownQueue;
		case 0x8000008e: return (uint32_t) &kernel_KeSaveFloatingPointState;
		case 0x8000008f: return (uint32_t) &kernel_KeSetBasePriorityThread;
		case 0x80000090: return (uint32_t) &kernel_KeSetDisableBoostThread;
		case 0x80000091: return (uint32_t) &kernel_KeSetEvent;
		case 0x80000092: return (uint32_t) &kernel_KeSetEventBoostPriority;
		case 0x80000093: return (uint32_t) &kernel_KeSetPriorityProcess;
		case 0x80000094: return (uint32_t) &kernel_KeSetPriorityThread;
		case 0x80000095: return (uint32_t) &kernel_KeSetTimer;
		case 0x80000096: return (uint32_t) &kernel_KeSetTimerEx;
		case 0x80000097: return (uint32_t) &kernel_KeStallExecutionProcessor;
		case 0x80000098: return (uint32_t) &kernel_KeSuspendThread;
		case 0x80000099: return (uint32_t) &kernel_KeSynchronizeExecution;
		case 0x8000009a: return (uint32_t) &kernel_KeSystemTime;
		case 0x8000009b: return (uint32_t) &kernel_KeTestAlertThread;
		case 0x8000009c: return (uint32_t) &kernel_KeTickCount;
		case 0x8000009d: return (uint32_t) &kernel_KeTimeIncrement;
		case 0x8000009e: return (uint32_t) &kernel_KeWaitForMultipleObjects;
		case 0x8000009f: return (uint32_t) &kernel_KeWaitForSingleObject;
		case 0x800000a0: return (uint32_t) &kernel_KfRaiseIrql;
		case 0x800000a1: return (uint32_t) &kernel_KfLowerIrql;
		case 0x800000a2: return (uint32_t) &kernel_KiBugCheckData;
		case 0x800000a3: return (uint32_t) &kernel_KiUnlockDispatcherDatabase;
		case 0x800000a4: return (uint32_t) &kernel_LaunchDataPage;
		case 0x800000a5: return (uint32_t) &kernel_MmAllocateContiguousMemory;
		case 0x800000a6: return (uint32_t) &kernel_MmAllocateContiguousMemoryEx;
		case 0x800000a7: return (uint32_t) &kernel_MmAllocateSystemMemory;
		case 0x800000a8: return (uint32_t) &kernel_MmClaimGpuInstanceMemory;
		case 0x800000a9: return (uint32_t) &kernel_MmCreateKernelStack;
		case 0x800000aa: return (uint32_t) &kernel_MmDeleteKernelStack;
		case 0x800000ab: return (uint32_t) &kernel_MmFreeContiguousMemory;
		case 0x800000ac: return (uint32_t) &kernel_MmFreeSystemMemory;
		case 0x800000ad: return (uint32_t) &kernel_MmGetPhysicalAddress;
		case 0x800000ae: return (uint32_t) &kernel_MmIsAddressValid;
		case 0x800000af: return (uint32_t) &kernel_MmLockUnlockBufferPages;
		case 0x800000b0: return (uint32_t) &kernel_MmLockUnlockPhysicalPage;
		case 0x800000b1: return (uint32_t) &kernel_MmMapIoSpace;
		case 0x800000b2: return (uint32_t) &kernel_MmPersistContiguousMemory;
		case 0x800000b3: return (uint32_t) &kernel_MmQueryAddressProtect;
		case 0x800000b4: return (uint32_t) &kernel_MmQueryAllocationSize;
		case 0x800000b5: return (uint32_t) &kernel_MmQueryStatistics;
		case 0x800000b6: return (uint32_t) &kernel_MmSetAddressProtect;
		case 0x800000b7: return (uint32_t) &kernel_MmUnmapIoSpace;
		case 0x800000b8: return (uint32_t) &kernel_NtAllocateVirtualMemory;
		case 0x800000b9: return (uint32_t) &kernel_NtCancelTimer;
		case 0x800000ba: return (uint32_t) &kernel_NtClearEvent;
		case 0x800000bb: return (uint32_t) &kernel_NtClose;
		case 0x800000bc: return (uint32_t) &kernel_NtCreateDirectoryObject;
		case 0x800000bd: return (uint32_t) &kernel_NtCreateEvent;
		case 0x800000be: return (uint32_t) &kernel_NtCreateFile;
		case 0x800000bf: return (uint32_t) &kernel_NtCreateIoCompletion;
		case 0x800000c0: return (uint32_t) &kernel_NtCreateMutant;
		case 0x800000c1: return (uint32_t) &kernel_NtCreateSemaphore;
		case 0x800000c2: return (uint32_t) &kernel_NtCreateTimer;
		case 0x800000c3: return (uint32_t) &kernel_NtDeleteFile;
		case 0x800000c4: return (uint32_t) &kernel_NtDeviceIoControlFile;
		case 0x800000c5: return (uint32_t) &kernel_NtDuplicateObject;
		case 0x800000c6: return (uint32_t) &kernel_NtFlushBuffersFile;
		case 0x800000c7: return (uint32_t) &kernel_NtFreeVirtualMemory;
		case 0x800000c8: return (uint32_t) &kernel_NtFsControlFile;
		case 0x800000c9: return (uint32_t) &kernel_NtOpenDirectoryObject;
		case 0x800000ca: return (uint32_t) &kernel_NtOpenFile;
		case 0x800000cb: return (uint32_t) &kernel_NtOpenSymbolicLinkObject;
		case 0x800000cc: return (uint32_t) &kernel_NtProtectVirtualMemory;
		case 0x800000cd: return (uint32_t) &kernel_NtPulseEvent;
		case 0x800000ce: return (uint32_t) &kernel_NtQueueApcThread;
		case 0x800000cf: return (uint32_t) &kernel_NtQueryDirectoryFile;
		case 0x800000d0: return (uint32_t) &kernel_NtQueryDirectoryObject;
		case 0x800000d1: return (uint32_t) &kernel_NtQueryEvent;
		case 0x800000d2: return (uint32_t) &kernel_NtQueryFullAttributesFile;
		case 0x800000d3: return (uint32_t) &kernel_NtQueryInformationFile;
		case 0x800000d4: return (uint32_t) &kernel_NtQueryIoCompletion;
		case 0x800000d5: return (uint32_t) &kernel_NtQueryMutant;
		case 0x800000d6: return (uint32_t) &kernel_NtQuerySemaphore;
		case 0x800000d7: return (uint32_t) &kernel_NtQuerySymbolicLinkObject;
		case 0x800000d8: return (uint32_t) &kernel_NtQueryTimer;
		case 0x800000d9: return (uint32_t) &kernel_NtQueryVirtualMemory;
		case 0x800000da: return (uint32_t) &kernel_NtQueryVolumeInformationFile;
		case 0x800000db: return (uint32_t) &kernel_NtReadFile;
		case 0x800000dc: return (uint32_t) &kernel_NtReadFileScatter;
		case 0x800000dd: return (uint32_t) &kernel_NtReleaseMutant;
		case 0x800000de: return (uint32_t) &kernel_NtReleaseSemaphore;
		case 0x800000df: return (uint32_t) &kernel_NtRemoveIoCompletion;
		case 0x800000e0: return (uint32_t) &kernel_NtResumeThread;
		case 0x800000e1: return (uint32_t) &kernel_NtSetEvent;
		case 0x800000e2: return (uint32_t) &kernel_NtSetInformationFile;
		case 0x800000e3: return (uint32_t) &kernel_NtSetIoCompletion;
		case 0x800000e4: return (uint32_t) &kernel_NtSetSystemTime;
		case 0x800000e5: return (uint32_t) &kernel_NtSetTimerEx;
		case 0x800000e6: return (uint32_t) &kernel_NtSignalAndWaitForSingleObjectEx;
		case 0x800000e7: return (uint32_t) &kernel_NtSuspendThread;
		case 0x800000e8: return (uint32_t) &kernel_NtUserIoApcDispatcher;
		case 0x800000e9: return (uint32_t) &kernel_NtWaitForSingleObject;
		case 0x800000ea: return (uint32_t) &kernel_NtWaitForSingleObjectEx;
		case 0x800000eb: return (uint32_t) &kernel_NtWaitForMultipleObjectsEx;
		case 0x800000ec: return (uint32_t) &kernel_NtWriteFile;
		case 0x800000ed: return (uint32_t) &kernel_NtWriteFileGather;
		case 0x800000ee: return (uint32_t) &kernel_NtYieldExecution;
		case 0x800000ef: return (uint32_t) &kernel_ObCreateObject;
		case 0x800000f0: return (uint32_t) &kernel_ObDirectoryObjectType;
		case 0x800000f1: return (uint32_t) &kernel_ObInsertObject;
		case 0x800000f2: return (uint32_t) &kernel_ObMakeTemporaryObject;
		case 0x800000f3: return (uint32_t) &kernel_ObOpenObjectByName;
		case 0x800000f4: return (uint32_t) &kernel_ObOpenObjectByPointer;
		case 0x800000f5: return (uint32_t) &kernel_ObpObjectHandleTable;
		case 0x800000f6: return (uint32_t) &kernel_ObReferenceObjectByHandle;
		case 0x800000f7: return (uint32_t) &kernel_ObReferenceObjectByName;
		case 0x800000f8: return (uint32_t) &kernel_ObReferenceObjectByPointer;
		case 0x800000f9: return (uint32_t) &kernel_ObSymbolicLinkObjectType;
		case 0x800000fa: return (uint32_t) &kernel_ObfDereferenceObject;
		case 0x800000fb: return (uint32_t) &kernel_ObfReferenceObject;
		case 0x800000fc: return (uint32_t) &kernel_PhyGetLinkState;
		case 0x800000fd: return (uint32_t) &kernel_PhyInitialize;
		case 0x800000fe: return (uint32_t) &kernel_PsCreateSystemThread;
		case 0x800000ff: return (uint32_t) &kernel_PsCreateSystemThreadEx;
		case 0x80000100: return (uint32_t) &kernel_PsQueryStatistics;
		case 0x80000101: return (uint32_t) &kernel_PsSetCreateThreadNotifyRoutine;
		case 0x80000102: return (uint32_t) &kernel_PsTerminateSystemThread;
		case 0x80000103: return (uint32_t) &kernel_PsThreadObjectType;
		case 0x80000104: return (uint32_t) &kernel_RtlAnsiStringToUnicodeString;
		case 0x80000105: return (uint32_t) &kernel_RtlAppendStringToString;
		case 0x80000106: return (uint32_t) &kernel_RtlAppendUnicodeStringToString;
		case 0x80000107: return (uint32_t) &kernel_RtlAppendUnicodeToString;
		case 0x80000108: return (uint32_t) &kernel_RtlAssert;
		case 0x80000109: return (uint32_t) &kernel_RtlCaptureContext;
		case 0x8000010a: return (uint32_t) &kernel_RtlCaptureStackBackTrace;
		case 0x8000010b: return (uint32_t) &kernel_RtlCharToInteger;
		case 0x8000010c: return (uint32_t) &kernel_RtlCompareMemory;
		case 0x8000010d: return (uint32_t) &kernel_RtlCompareMemoryUlong;
		case 0x8000010e: return (uint32_t) &kernel_RtlCompareString;
		case 0x8000010f: return (uint32_t) &kernel_RtlCompareUnicodeString;
		case 0x80000110: return (uint32_t) &kernel_RtlCopyString;
		case 0x80000111: return (uint32_t) &kernel_RtlCopyUnicodeString;
		case 0x80000112: return (uint32_t) &kernel_RtlCreateUnicodeString;
		case 0x80000113: return (uint32_t) &kernel_RtlDowncaseUnicodeChar;
		case 0x80000114: return (uint32_t) &kernel_RtlDowncaseUnicodeString;
		case 0x80000115: return (uint32_t) &kernel_RtlEnterCriticalSection;
		case 0x80000116: return (uint32_t) &kernel_RtlEnterCriticalSectionAndRegion;
		case 0x80000117: return (uint32_t) &kernel_RtlEqualString;
		case 0x80000118: return (uint32_t) &kernel_RtlEqualUnicodeString;
		case 0x80000119: return (uint32_t) &kernel_RtlExtendedIntegerMultiply;
		case 0x8000011a: return (uint32_t) &kernel_RtlExtendedLargeIntegerDivide;
		case 0x8000011b: return (uint32_t) &kernel_RtlExtendedMagicDivide;
		case 0x8000011c: return (uint32_t) &kernel_RtlFillMemory;
		case 0x8000011d: return (uint32_t) &kernel_RtlFillMemoryUlong;
		case 0x8000011e: return (uint32_t) &kernel_RtlFreeAnsiString;
		case 0x8000011f: return (uint32_t) &kernel_RtlFreeUnicodeString;
		case 0x80000120: return (uint32_t) &kernel_RtlGetCallersAddress;
		case 0x80000121: return (uint32_t) &kernel_RtlInitAnsiString;
		case 0x80000122: return (uint32_t) &kernel_RtlInitUnicodeString;
		case 0x80000123: return (uint32_t) &kernel_RtlInitializeCriticalSection;
		case 0x80000124: return (uint32_t) &kernel_RtlIntegerToChar;
		case 0x80000125: return (uint32_t) &kernel_RtlIntegerToUnicodeString;
		case 0x80000126: return (uint32_t) &kernel_RtlLeaveCriticalSection;
		case 0x80000127: return (uint32_t) &kernel_RtlLeaveCriticalSectionAndRegion;
		case 0x80000128: return (uint32_t) &kernel_RtlLowerChar;
		case 0x80000129: return (uint32_t) &kernel_RtlMapGenericMask;
		case 0x8000012a: return (uint32_t) &kernel_RtlMoveMemory;
		case 0x8000012b: return (uint32_t) &kernel_RtlMultiByteToUnicodeN;
		case 0x8000012c: return (uint32_t) &kernel_RtlMultiByteToUnicodeSize;
		case 0x8000012d: return (uint32_t) &kernel_RtlNtStatusToDosError;
		case 0x8000012e: return (uint32_t) &kernel_RtlRaiseException;
		case 0x8000012f: return (uint32_t) &kernel_RtlRaiseStatus;
		case 0x80000130: return (uint32_t) &kernel_RtlTimeFieldsToTime;
		case 0x80000131: return (uint32_t) &kernel_RtlTimeToTimeFields;
		case 0x80000132: return (uint32_t) &kernel_RtlTryEnterCriticalSection;
		case 0x80000133: return (uint32_t) &kernel_RtlUlongByteSwap;
		case 0x80000134: return (uint32_t) &kernel_RtlUnicodeStringToAnsiString;
		case 0x80000135: return (uint32_t) &kernel_RtlUnicodeStringToInteger;
		case 0x80000136: return (uint32_t) &kernel_RtlUnicodeToMultiByteN;
		case 0x80000137: return (uint32_t) &kernel_RtlUnicodeToMultiByteSize;
		case 0x80000138: return (uint32_t) &kernel_RtlUnwind;
		case 0x80000139: return (uint32_t) &kernel_RtlUpcaseUnicodeChar;
		case 0x8000013a: return (uint32_t) &kernel_RtlUpcaseUnicodeString;
		case 0x8000013b: return (uint32_t) &kernel_RtlUpcaseUnicodeToMultiByteN;
		case 0x8000013c: return (uint32_t) &kernel_RtlUpperChar;
		case 0x8000013d: return (uint32_t) &kernel_RtlUpperString;
		case 0x8000013e: return (uint32_t) &kernel_RtlUshortByteSwap;
		case 0x8000013f: return (uint32_t) &kernel_RtlWalkFrameChain;
		case 0x80000140: return (uint32_t) &kernel_RtlZeroMemory;
		case 0x80000141: return (uint32_t) &kernel_XboxEEPROMKey;
		case 0x80000142: return (uint32_t) &kernel_XboxHardwareInfo;
		case 0x80000143: return (uint32_t) &kernel_XboxHDKey;
		case 0x80000144: return (uint32_t) &kernel_XboxKrnlVersion;
		case 0x80000145: return (uint32_t) &kernel_XboxSignatureKey;
		case 0x80000146: return (uint32_t) &kernel_XeImageFileName;
		case 0x80000147: return (uint32_t) &kernel_XeLoadSection;
		case 0x80000148: return (uint32_t) &kernel_XeUnloadSection;
		case 0x80000149: return (uint32_t) &kernel_READ_PORT_BUFFER_UCHAR;
		case 0x8000014a: return (uint32_t) &kernel_READ_PORT_BUFFER_USHORT;
		case 0x8000014b: return (uint32_t) &kernel_READ_PORT_BUFFER_ULONG;
		case 0x8000014c: return (uint32_t) &kernel_WRITE_PORT_BUFFER_UCHAR;
		case 0x8000014d: return (uint32_t) &kernel_WRITE_PORT_BUFFER_USHORT;
		case 0x8000014e: return (uint32_t) &kernel_WRITE_PORT_BUFFER_ULONG;
		case 0x8000014f: return (uint32_t) &kernel_XcSHAInit;
		case 0x80000150: return (uint32_t) &kernel_XcSHAUpdate;
		case 0x80000151: return (uint32_t) &kernel_XcSHAFinal;
		case 0x80000152: return (uint32_t) &kernel_XcRC4Key;
		case 0x80000153: return (uint32_t) &kernel_XcRC4Crypt;
		case 0x80000154: return (uint32_t) &kernel_XcHMAC;
		case 0x80000155: return (uint32_t) &kernel_XcPKEncPublic;
		case 0x80000156: return (uint32_t) &kernel_XcPKDecPrivate;
		case 0x80000157: return (uint32_t) &kernel_XcPKGetKeyLen;
		case 0x80000158: return (uint32_t) &kernel_XcVerifyPKCS1Signature;
		case 0x80000159: return (uint32_t) &kernel_XcModExp;
		case 0x8000015a: return (uint32_t) &kernel_XcDESKeyParity;
		case 0x8000015b: return (uint32_t) &kernel_XcKeyTable;
		case 0x8000015c: return (uint32_t) &kernel_XcBlockCrypt;
		case 0x8000015d: return (uint32_t) &kernel_XcBlockCryptCBC;
		case 0x8000015e: return (uint32_t) &kernel_XcCryptService;
		case 0x8000015f: return (uint32_t) &kernel_XcUpdateCrypto;
		case 0x80000160: return (uint32_t) &kernel_RtlRip;
		case 0x80000161: return (uint32_t) &kernel_XboxLANKey;
		case 0x80000162: return (uint32_t) &kernel_XboxAlternateSignatureKeys;
		case 0x80000163: return (uint32_t) &kernel_XePublicKeyData;
		case 0x80000164: return (uint32_t) &kernel_HalBootSMCVideoMode;
		case 0x80000165: return (uint32_t) &kernel_IdexChannelObject;
		case 0x80000166: return (uint32_t) &kernel_HalIsResetOrShutdownPending;
		case 0x80000167: return (uint32_t) &kernel_IoMarkIrpMustComplete;
		case 0x80000168: return (uint32_t) &kernel_HalInitiateShutdown;
		case 0x80000169: return (uint32_t) &kernel_snprintf;
		case 0x8000016a: return (uint32_t) &kernel_sprintf;
		case 0x8000016b: return (uint32_t) &kernel_vsnprintf;
		case 0x8000016c: return (uint32_t) &kernel_vsprintf;
		case 0x8000016d: return (uint32_t) &kernel_HalEnableSecureTrayEject;
		case 0x8000016e: return (uint32_t) &kernel_HalWriteSMCScratchRegister;
		default:
			log("Unknown id to thunk_lookup %08x", id);
			halt();
			return 0;
	}
}
